# See https://conda.io/docs/building/meta-yaml.html
# for more information about this file.

about:
  summary: "ESA CCI Toolbox (Cate)"
  home: https://github.com/CCI-Tools/cate
  license: MIT
  license_file: LICENSE

package:
  name: cate
  # Not released/deployed yet! Use PEP 440 versioning scheme
  # ref: https://www.python.org/dev/peps/pep-0440/#developmental-releases
  # e.g.
  # 0.7.0.dev1
  # 1.0.0
  version: "2.0.0.dev18"

build:
  number: 0
  entry_points:
    # Put any entry points (scripts to be generated automatically) here.
    - cate = cate.cli.main:main
    - cate-webapi-start = cate.webapi.start:main
    - cate-webapi-stop = cate.webapi.stop:main

source:
  # git_rev: v0.7.0a1
  git_url: https://github.com/CCI-Tools/cate.git
  # Uncomment to skip the "git clone" step
  # path: ../../../cate

requirements:
  build:
    - python 3.6*
    #
    # dependencies (in alphabetical order)
    #
    - cartopy >=0.15,<1.0
    - conda >=4.5.1,<5.0
    # Include Cython, otherwise pip will do so during "python setup.py install" (why???)
    - cython >=0.25,<1.0
    - dask >=0.19,<1.0
    - fiona >=1.7,<2.0
    - gdal >=2.2.3,<3.0
    - geopandas >=0.3,<1.0
    # require specific minor version to prevent downgrade
    - geos >=3.5.1,<4.0
    # require specific minor version to prevent downgrade
    - hdf4 >=4.2.12,<5.0
    - h5netcdf >=0.4.2,<1.0
    - jdcal >=1.3,<2.0
    - matplotlib >=2.2,<3.0
    - netcdf4 >=1.2,<2.0
    - numba >=0.33,<1.0
    # Starting from numpy 1.13 xarray ufuncs are deprecated, as np ufuncs work across dask datasets
    - numpy >=1.13,<2.0
    - owslib >=0.14,<1.0
    - pandas >=0.22,<1.0
    - pillow >=5.0,<6.0
    - psutil >=5.2,<6.0
    - pyproj >=1.9,<2.0
    - pyqt >=5.6,<6.0
    - pyshp >=1.2,<2.0
    - python-dateutil >=2.6,<3.0
    - scipy >=0.19,<1.0
    - shapely >=1.6,<2.0
    - tornado >=5.0,<6.0
    # xarray >= 0.10.1 has an issue with time decoding see #579
    - xarray ==0.10.0
    #
    # build
    - setuptools
    - pytest
    - pytest-cov

  run:
    - python 3.6*
    #
    # dependencies (in alphabetical order)
    #
    - cartopy >=0.15,<1.0
    - conda >=4.5.1,<5.0
    # Include Cython, otherwise pip will do so during "python setup.py install" (why???)
    - cython >=0.25,<1.0
    - dask >=0.15.4,<1.0
    - fiona >=1.7,<2.0
    - gdal >=2.2.3,<3.0
    - geopandas >=0.3,<1.0
    # require specific minor version to prevent downgrade
    - geos >=3.5.1,<4.0
    # require specific minor version to prevent downgrade
    - hdf4 >=4.2.12,<5.0
    - h5netcdf >=0.4.2,<1.0
    - jdcal >=1.3,<2.0
    - matplotlib >=2.2,<3.0
    - netcdf4 >=1.2,<2.0
    - numba >=0.33,<1.0
    # Starting from numpy 1.13 xarray ufuncs are deprecated, as np ufuncs work across dask datasets
    - numpy >=1.13,<2.0
    - owslib >=0.14,<1.0
    - pandas >=0.22,<1.0
    - pillow >=5.0,<6.0
    - psutil >=5.2,<6.0
    - pyproj >=1.9,<2.0
    - pyqt >=5.6,<6.0
    - pyshp >=1.2,<2.0
    - python-dateutil >=2.6,<3.0
    - scipy >=0.19,<1.0
    - shapely >=1.6,<2.0
    - tornado >=5.0,<6.0
    # xarray >= 0.10.1 has an issue with time decoding see #579
    - xarray ==0.10.0

test:
  # Python imports
  imports:
    - cate.cli.main
    - cate.webapi.main

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - cate --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.
    - pytest
    - pytest-cov
