# See https://conda.io/docs/building/meta-yaml.html
# for more information about this file.

about:
  summary: "ESA CCI Toolbox (Cate)"
  home: https://github.com/CCI-Tools/cate
  license: MIT
  license_file: LICENSE

package:
  name: cate
  # Not released/deployed yet! Use PEP 440 versioning scheme
  # ref: https://www.python.org/dev/peps/pep-0440/#developmental-releases
  # e.g.
  # 0.7.0.dev1
  # 0.7.0rc1
  # 0.7.0rc1.dev1
  version: "1.0.0.dev2"

build:
  number: 0
  entry_points:
    # Put any entry points (scripts to be generated automatically) here.
    - cate = cate.cli.main:main
    - cate-webapi = cate.webapi.main:main

source:
  # git_rev: v0.7.0a1
  git_url: https://github.com/CCI-Tools/cate.git
  # Uncomment to skip the "git clone" step
  # path: ../../../cate

requirements:
  build:
    - python 3.6*
    #
    # dependencies (in alphabetical order)
    #
    - cartopy >=0.15
    # Include cython, otherwise pip will do so during "python setup.py install" (why???)
    - cython >=0.25
    # dask 0.15.3 broke the build
    - dask >=0.15.0,<=0.15.2
    - fiona >=1.7
    - geopandas >=0.2
    # require specific minor version to prevent downgrade
    - geos >=3.5.1
    # require specific minor version to prevent downgrade
    - hdf4 >=4.2.12
    - jdcal >=1.3
    - matplotlib >=2.0
    - netcdf4 >=1.2
    - numba >=0.33
    # numpy 1.12 gave some trouble
    - numpy >=1.11
    - owslib >=0.14
    - pandas >=0.19
    - pillow >=4.1
    - psutil >=5.2
    - pyproj >=1.9
    - pyqt >=5.6
    - python-dateutil >=2.6
    - scipy >=0.19
    - shapely >=1.5
    - tornado >=4.5
    - xarray >=0.9
    #
    # build
    - setuptools
    - pytest
    - pytest-cov

  run:
    - python 3.6*
    #
    # dependencies (in alphabetical order)
    #
    - cartopy >=0.15
    # Include cython, otherwise pip will do so during "python setup.py install" (why???)
    - cython >=0.25
    # dask 0.15.3 broke the build
    - dask >=0.15.0,<=0.15.2
    - fiona >=1.7
    - geopandas >=0.2
    # require specific minor version to prevent downgrade
    - geos >=3.5.1
    # require specific minor version to prevent downgrade
    - hdf4 >=4.2.12
    - h5netcdf >=0.4.2
    - jdcal >=1.3
    - matplotlib >=2.0
    - netcdf4 >=1.2
    - numba >=0.33
    # numpy 1.12 gave some trouble
    - numpy >=1.11
    - owslib >=0.14
    - pandas >=0.19
    - pillow >=4.1
    - pyproj >=1.9
    - pyqt >=5.6
    - pyshp >=1.2
    - python-dateutil >=2.6
    - scipy >=0.19
    - shapely >=1.5
    - tornado >=4.5
    - xarray >=0.9


test:
  # Python imports
  imports:
    - cate.cli.main
    - cate.webapi.main

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - cate --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.
    - pytest
    - pytest-cov
