# See https://conda.io/docs/building/meta-yaml.html
# for more information about this file.

{% set version = "2.0.0" %}

package:
  name: cate
  version: "{{ version }}"

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    # Put any entry points (scripts to be generated automatically) here.
    - cate = cate.cli.main:main
    - cate-webapi-start = cate.webapi.start:main
    - cate-webapi-stop = cate.webapi.stop:main

source:
    url: "https://github.com/CCI-Tools/cate/archive/v{{ version }}.tar.gz"
    sha256: 046bb37c24a694678ecf8221c057817511f488073aea6f5394a604e86f5dd166

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    # Runtime libs
    - bokeh>=1.0.2
    - boto3>=1.9.65
    - botocore>=1.12.66
    - cartopy>=0.17.0
    - cython>=0.29.2
    - dask>=1.0.0
    - fiona>=1.8.4
    - geopandas>=0.4.0
    - geos>=3.7.1
    - geotiff>=1.4.2
    - h5netcdf>=0.6.2
    - h5py>=2.8.0
    - hdf4>=4.2.13
    - hdf5>=1.10.4
    - jdcal>=1.4
    - matplotlib>=3.0.2
    - numba>=0.41.0
    - numpy>=1.15.4
    - netcdf4>=1.4.2
    - owslib>=0.17.0
    - pandas>=0.23.4
    - pillow>=5.3.0
    - pip>=18.1
    - psutil>=5.4.8
    - pyepsg>=0.4.0
    - pyproj>=1.9.5
    - pyshp>=2.0.0
    - python-dateutil>=2.7.5
    - s3transfer>=0.1.13
    - scipy>=1.1.0
    - setuptools>=40.6.3
    - shapely>=1.6.4
    - tornado>=5.1.1
    - xarray>=0.12
    - yaml>=0.1.7

test:
  # Python imports
  imports:
    - cate
    - cate.core
    - cate.core.ds
    - cate.core.op
    - cate.core.workflow
    - cate.core.objectio
    - cate.core.workspace
    - cate.util
    - cate.ds
    - cate.ops
    - cate.cli
    - cate.webapi
    - cate.util.cache
    - cate.util.cli
    - cate.util.extend
    - cate.util.im
    - cate.util.misc
    - cate.util.monitor
    - cate.util.namespace
    - cate.util.opmetainf
    - cate.util.process
    - cate.util.safe
    - cate.util.tmpfile
    - cate.util.undefined
    - cate.util.web

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - cate --help


about:
  summary: "ESA CCI Toolbox (Cate) with CLI"
  description: "The CCI Toolbox (Cate) is a software environment for ingesting, operating on and visualising all ESA
  Climate Change Initiative data."
  home: https://climatetoolbox.io
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://cate.readthedocs.io
  dev_url: https://github.com/CCI-Tools/cate