package:
  name: cate
  version: "0.6.0a2"

build:
  #string: 'rc0'
  number: 0
  # noarch_python: False
  # preserve_egg_dir: False
  # osx_is_app: False
  entry_points:
    # Put any entry points (scripts to be generated automatically) here.
    - cate = cate.ui.cli:main
    - cate-webapi = cate.ui.webapi:main

source:
  # git_rev: v0.6.0a1
  #git_url: https://github.com/CCI-Tools/cate-core.git
  # Uncomment to skip the "git clone" step
  path: ../../cate-core

requirements:
  build:
    - python 3.5*
    - setuptools
    - pytest
    - pytest-cov

    - pyqt 5.6*
    - matplotlib
    - xarray
    - dask
    - numpy
    - scipy
    - netcdf4
    - numba
    - pandas
    - cartopy
    - pillow 3.4.2
    - hdf4 4.2.12
    - basemap
    - tornado
    - jdcal

  run:
    - python 3.5*
    - menuinst    # [win]

    - pyqt 5.6*
    - matplotlib
    - xarray
    - dask
    - numpy
    - scipy
    - netcdf4
    - numba
    - pandas
    - cartopy
    - pillow  3.4.2
    - hdf4 4.2.12
    - basemap
    - tornado
    - jdcal

test:
  # Python imports
  imports:
    - cate
    - cate.core
    - cate.core.ds
    - cate.core.op
    - cate.core.workflow
    - cate.core.objectio
    - cate.core.util
    - cate.ds
    - cate.ops
    - cate.ui
    - cate.ui.cli
    - cate.ui.workspace
    - cate.ui.webapi

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - cate --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.
    - pytest
    - pytest-cov

# The app section is for creating entries in the Anaconda Launcher / Navigator
app:
  entry: open ${PREFIX}/Scripts/cate-cli.bat      # [win]
  entry: open ${PREFIX}/bin/cate-cli.command      # [osx]
  entry: open ${PREFIX}/bin/cate-cli.sh           # [unix]
  icon: cate.png
  own_environment: False
  summary:  "ESA CCI Toolbox (Cate)"

about:
  home: https://github.com/CCI-Tools/cate-core
  license: MIT
  license_file: LICENSE.md
  summary: "ESA CCI Toolbox (Cate)"



# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
