language: generic

env:
  - CONDA_PY=3.5

os:
  - linux
  - osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda info -a
  - conda install conda-build

script:
  - conda build --output-folder cate-packages -c conda-forge -c defaults recipes/cate
  - conda build --output-folder cate-packages -c conda-forge -c defaults recipes/cate-cli
  - conda build --output-folder cate-packages -c conda-forge -c defaults recipes/cate-lib
  - conda build --output-folder cate-packages -c conda-forge -c defaults recipes/cate-util

#  TODO (forman): upload packages to anaconda package repo
