# version 2.0.0, b1

language: shell

env:
  global:
    - CONDA_PY=3.7

os:
  - linux
  - osx
  - windows

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install -y openssl;
      choco install -y miniconda3;
      export PATH="/c/tools/miniconda3/Scripts:$PATH";
      source activate base;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
    fi
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set channel_priority strict
  - conda update conda
  - conda info -a
  - conda install conda-verify conda-build anaconda-client

script:
  - conda build -c conda-forge recipes/cate


deploy:
  # Deploy to Anaconda.org
  - provider: script
    script: bash ./deploy_to_anaconda.sh deploy
    on:
      # tags: true
      all_branches: true
    skip_cleanup: true

