# version 2.0.0.dev13, b1

language: generic

env:
  global:
    - CONDA_PY=3.6

os:
  - linux
  - osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda info -a
  - conda install conda-build anaconda-client

script:
  #- conda build --old-build-string -c conda-forge -c defaults recipes/cate
  #- ./upload_to_anaconda_cloud.sh cate
  #
  - conda build --old-build-string -c conda-forge -c defaults recipes/cate-cli
  - ./upload_to_anaconda_cloud.sh cate-cli
  #
  #- conda build --old-build-string -c conda-forge -c defaults recipes/cate-util
  #- ./upload_to_anaconda_cloud.sh cate-util
