# version here is only relevant for the AppVeyor CI, no need to adjust
version: '{build}'

environment:
  global:
    PYTHON_LOC: "C:\\Miniconda37-x64"

install:
  - call %PYTHON_LOC%\Scripts\activate.bat
  - conda config --set always_yes yes --set changeps1 no --set channel_priority strict
  - conda install -y anaconda-client

build_script:
  - set MPLCONFIGDIR="."
  - conda build --old-build-string -c conda-forge recipes\cate


