version: '0.7.0.dev1'

build: off

branches:
  only:
    - master

install:
  - set PATH=C:\Miniconda35-x64;C:\Miniconda35-x64\Scripts;%PATH%
  - conda build --output-folder cate-packages -c conda-forge -c defaults recipes\cate
  - conda build --output-folder cate-packages -c conda-forge -c defaults recipes\cate-cli
  - conda build --output-folder cate-packages -c conda-forge -c defaults recipes\cate-lib
  - conda build --output-folder cate-packages -c conda-forge -c defaults recipes\cate-util

platform:
  - x86
  - x64

matrix:
  fast_finish: true

artifacts:
  - path: '*.exe'
    name: cate-installer-exe

#  TODO (forman): upload packages to anaconda package repo

