version: '0.7.0.dev1.{build}'

environment:
  global:
    # Example can be found here https://github.com/quantopian/zipline/blob/master/appveyor.yml
    ANACONDA_TOKEN:
      secure: "Whb/T2fL16t975pbtx8lsc38bvrzbrdmqofy8zLhKDcRPNNaFoFq2IfJWiF29kac"
    PYTHON_LOC: "C:\\Miniconda35-x64"
    INSTALLER_VERSION: "0.7.0.dev1"

install:
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda install -y conda-build constructor anaconda-client

build_script:
  - cmd: conda build -c conda-forge -c defaults recipes\cate
  - cmd: conda build -c conda-forge -c defaults recipes\cate-cli
  - cmd: conda build -c conda-forge -c defaults recipes\cate-lib
  - cmd: conda build -c conda-forge -c defaults recipes\cate-util

deploy_script:
  #- cmd: anaconda -v -t %ANACONDA_TOKEN% upload "%PYTHON_LOC%\conda-bld\win-64\cate*.tar.bz2" -u ccitools --force
  # only publish artifacts on master branch when pushed (not from cron or PRs)
  - ps: >-
      if(!$env:APPVEYOR_SCHEDULED_BUILD -and !$env:appveyor_pull_request_number -and $env:APPVEYOR_REPO_BRANCH -eq 'master') {
        anaconda -v -t $env:ANACONDA_TOKEN upload $env:PYTHON_LOC\conda-bld\win-64\cate*.tar.bz2 -u ccitools --force
      }

