version: '0.7.0.dev1.{build}'

environment:
  global:
    # Example can be found here https://github.com/quantopian/zipline/blob/master/appveyor.yml
    ANACONDA_TOKEN:
      secure: "Whb/T2fL16t975pbtx8lsc38bvrzbrdmqofy8zLhKDcRPNNaFoFq2IfJWiF29kac"
    PYTHON_LOC: "C:\\Miniconda35-x64"
    INSTALLER_VERSION: "0.7.0.dev1"

install:
  - call %PYTHON_LOC%\Scripts\activate.bat
  - conda config --set always_yes yes --set changeps1 no
  - conda install -y conda-build constructor anaconda-client

build_script:
  # appveyor has no HOME directory set, this leads to an error in matplotlib
  - set MPLCONFIGDIR="."
  - conda build --no-test -c conda-forge -c defaults recipes\cate
  - conda build --no-test -c conda-forge -c defaults recipes\cate-cli
  - conda build --no-test -c conda-forge -c defaults recipes\cate-lib
  - conda build --no-test -c conda-forge -c defaults recipes\cate-util
  # test are disbaled on appveyor: matplotlib fails, because no writable HOME directory

deploy_script:
  #- anaconda -v -t %ANACONDA_TOKEN% upload "%PYTHON_LOC%\conda-bld\win-64\cate*.tar.bz2" -u ccitools --force
  # only publish artifacts on master branch when pushed (not from cron or PRs)
  - ps: |
      if ( $env:APPVEYOR_SCHEDULED_BUILD -eq "True" ) {
          return
      }
      if ([bool]$env:APPVEYOR_PULL_REQUEST_NUMBER) {
          return
      }
      if ($env:APPVEYOR_REPO_BRANCH -eq 'master') {
          anaconda -v -t $env:ANACONDA_TOKEN upload "$env:PYTHON_LOC\conda-bld\win-64\cate*.tar.bz2" -u ccitools --force
      }

