# See https://conda.io/docs/building/meta-yaml.html
# for more information about this file.

about:
  summary: "ESA CCI Toolbox (Cate) command-line interface"
  home: https://github.com/CCI-Tools/cate-core
  license: MIT
  license_file: LICENSE

package:
  name: cate-cli
  # Not released/deployed yet! Use PEP 440 versioning scheme
  # ref: https://www.python.org/dev/peps/pep-0440/#developmental-releases
  version: "0.7.0.dev1"

build:
  number: 2
  entry_points:
    # Put any entry points (scripts to be generated automatically) here.
    - cate = cate.cli.main:main
    - cate-webapi = cate.webapi.main:main

source:
  # git_rev: v0.6.0a1
  #git_url: https://github.com/CCI-Tools/cate-core.git
  git_url: https://github.com/CCI-Tools/cate-core.git
  # Uncomment to skip the "git clone" step
  # path: ../../../cate-core

requirements:
  build:
    - python >=3.5
    - numpy >=1.11
    #
    - setuptools
    - pytest
    - pytest-cov
    #
    - cartopy
    - certifi ==2016.9.26
    - dask >=0.14
    - geopandas >=0.2
    - jdcal >=1.3
    - matplotlib >=1.5,<2
    - netcdf4 >=1.2
    - numba >=0.26
    - pandas >=0.18
    - pillow >=4.0
    - pyqt >=4.0,<5
    - scipy >=0.17
    - tornado >=4.4
    - xarray >=0.9.1
    #
    # for these packages specific version are needed, lower minor version have errors
    # they often get downgraded if not required explicitly
    - hdf4 >=4.2.12
    - geos >=3.5.1

  run:
    - python >=3.5
    - numpy >=1.11
    #
    - menuinst    # [win]
    #
    - cartopy
    - certifi ==2016.9.26
    - dask >=0.14
    - geopandas >=0.2
    - jdcal >=1.3
    - matplotlib >=1.5,<2
    - netcdf4 >=1.2
    - numba >=0.26
    - pandas >=0.18
    - pillow >=4.0
    - pyqt >=4.0,<5
    - scipy >=0.17
    - tornado >=4.4
    - xarray >=0.9.1
    #
    # for these packages specific version are needed, lower minor version have errors
    # they often get downgraded if not required explicitly
    - hdf4 >=4.2.12
    - geos >=3.5.1

test:
  # Python imports
  imports:
    - cate
    - cate.core
    - cate.core.ds
    - cate.core.op
    - cate.core.workflow
    - cate.core.objectio
    - cate.core.workspace
    - cate.util
    - cate.ds
    - cate.ops
    - cate.cli
    - cate.webapi

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - cate --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.
    - pytest
    - pytest-cov

# The app section is for creating entries in the Anaconda Launcher / Navigator
app:
  entry: open ${PREFIX}/Scripts/cate-cli.bat      # [win]
  entry: open ${PREFIX}/bin/cate-cli.command      # [osx]
  entry: open ${PREFIX}/bin/cate-cli.sh           # [linux]
  icon: cate.png
  own_environment: False
  summary:  "ESA CCI Toolbox (Cate) command-line interface"
