# See https://conda.io/docs/building/meta-yaml.html
# for more information about this file.

about:
  summary: "ESA CCI Toolbox (Cate), library only"
  home: https://github.com/CCI-Tools/cate-core
  license: MIT
  license_file: LICENSE

package:
  name: cate-lib
  # Not released/deployed yet! Use PEP 440 versioning scheme
  # ref: https://www.python.org/dev/peps/pep-0440/#developmental-releases
  version: "0.7.0.dev1"

build:
  number: 2

source:
  # git_rev: v0.7.0a1
  #git_url: https://github.com/CCI-Tools/cate-core.git
  git_url: https://github.com/CCI-Tools/cate-core.git
  # Uncomment to skip the "git clone" step
  # path: ../../../cate-core

requirements:
  build:
    - python 3.5*
    - setuptools
    - pytest
    - pytest-cov

    - pyqt 5.6*
    - matplotlib
    - xarray
    - dask
    - numpy
    - scipy
    - netcdf4
    - numba
    - pandas
    - cartopy
    - pillow >=3.4,<4
    - tornado >=4.4,<5
    - jdcal

  run:
    - python 3.5*

    - pyqt 5.6*
    - matplotlib
    - xarray
    - dask
    - numpy
    - scipy
    - netcdf4
    - numba
    - pandas
    - cartopy
    - pillow  >=3.4,<4
    - tornado >=4.4,<5
    - jdcal

test:
  # Python imports
  imports:
    - cate
    - cate.core
    - cate.ops
    - cate.ds
    - cate.util
    - cate.webapi

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.
    - pytest
    - pytest-cov
