# See https://conda.io/docs/building/meta-yaml.html
# for more information about this file.

about:
  summary: "ESA CCI Toolbox (Cate), just the utilities"
  home: https://github.com/CCI-Tools/cate
  license: MIT
  license_file: LICENSE

package:
  name: cate-util
  # Not released/deployed yet! Use PEP 440 versioning scheme
  # ref: https://www.python.org/dev/peps/pep-0440/#developmental-releases
  # e.g.
  # 0.7.0.dev1
  # 0.7.0rc1
  # 0.7.0rc1.dev1
  version: "1.0.0.dev2"

build:
  number: 0

source:
  # git_rev: v0.7.0a1
  # git_url: https://github.com/CCI-Tools/cate.git
  git_url: https://github.com/CCI-Tools/cate.git
  # Uncomment to skip the "git clone" step
  # path: ../../../cate

requirements:
  build:
    - python >=3.5
    - numpy 1.11*
    - setuptools
    - matplotlib 1.5*
    - pillow >=4.0
    - tornado >=4.4,<5

  run:
    - python >=3.5
    - numpy 1.11*

test:
  requires:
    - python >=3.5
    - numpy 1.11*
    - setuptools
    - matplotlib 1.5*
    - pillow >=4.0
    - tornado >=4.4,<5

  # Python imports
  imports:
    - cate.util
    - cate.util.im
    - cate.util.web
