# See https://conda.io/docs/building/meta-yaml.html
# for more information about this file.

about:
  summary: "ESA CCI Toolbox (Cate), just the utilities"
  home: https://github.com/CCI-Tools/cate
  license: MIT
  license_file: LICENSE

package:
  name: cate-util
  # Not released/deployed yet! Use PEP 440 versioning scheme
  # ref: https://www.python.org/dev/peps/pep-0440/#developmental-releases
  # e.g.
  # 0.7.0.dev1
  # 1.0.0
  version: "2.0.0.dev17"

build:
  number: 0

source:
  # git_rev: v0.7.0a1
  # git_url: https://github.com/CCI-Tools/cate.git
  git_url: https://github.com/CCI-Tools/cate.git
  # Uncomment to skip the "git clone" step
  # path: ../../../cate

requirements:
  run:
    # cate.util.* shall have no other dependencies, exceptions are cate.util.im, cate.util.web (see below)
    - python >=3.5

  build:
    - python >=3.5
    - setuptools
    # cate.util.im dependencies
    - matplotlib >=2.2,<3.0
    - numpy 1.13*
    - pillow >=5.0,<6.0
    # cate.util.web dependency
    - tornado >=5.0,<6.0

test:
  requires:
    - python >=3.5
    - setuptools
    # cate.util.im dependencies
    - matplotlib >=2.2,<3.0
    - numpy 1.13*
    - pillow >=5.0,<6.0
    # cate.util.web dependency
    - tornado >=5.0,<6.0

  # Python imports
  imports:
    - cate.util.cache
    - cate.util.cli
    - cate.util.extend
    - cate.util.im
    - cate.util.misc
    - cate.util.monitor
    - cate.util.namespace
    - cate.util.opmetainf
    - cate.util.process
    - cate.util.safe
    - cate.util.tmpfile
    - cate.util.undefined
    - cate.util.web
