# See https://conda.io/docs/building/meta-yaml.html
# for more information about this file.

about:
  summary: "ESA CCI Toolbox (Cate), just the utilities"
  home: https://github.com/CCI-Tools/cate-core
  license: MIT
  license_file: LICENSE.md

package:
  name: cate-util
  # Not released/deployed yet!
  version: "0.7.0a4"

build:
  number: 2

source:
  # git_rev: v0.7.0a1
  # git_url: https://github.com/CCI-Tools/cate-core.git
  # Uncomment to skip the "git clone" step
  path: ../../../cate-core


requirements:
  build:
    - python 3.5*
    - setuptools

    - matplotlib >=1.5,<2
    - numpy >=1.11,<2
    - pillow >=3.4,<4
    - tornado >=4.4,<5

  run:
    - python 3.5*

    - matplotlib >=1.5,<2
    - numpy >=1.11,<2
    - pillow >=3.4,<4
    - tornado >=4.4,<5

test:
  # Python imports
  imports:
    - cate.util
    - cate.util.im
    - cate.util.web
